Terminal navigation compatibility with linux
nicknisi/dotfiles pull request #154
Opened 2020-08-19 15:59 UTC by ajr-dev

2020-09-17 20:56 UTC, nicknisi requested changes

2020-09-17 20:56 UTC, nicknisi commented on zsh/zshrc.symlink
> +prepend_path $HOME/.local/bin
Can you remove this for the PR? It's not a directory that's set up by the install script and nothing from this setup is going in there.
```suggestion
```

2020-09-19 12:11 UTC, ajr-dev commented
I removed `$HOME/.local/bin` from the zshrc. That path is used when installing python modules with `pip --user` that's why I have it  in my zshrc.

2020-09-22 18:24 UTC, nicknisi approved these changes

2020-09-22 18:24 UTC, merged